In [10]:
import numpy as np
x = np.array([[12,5,2,4],
              [7,6,8,8],
              [1,6,7,7]])
z = x[:2,:3]
z

array([[12,  5,  2],
       [ 7,  6,  8]])

In [12]:
x[:2,:]

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8]])

In [13]:
x[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [14]:
x[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [15]:
x[:,0]

array([12,  7,  1])

In [16]:
x[0,:]

array([12,  5,  2,  4])

In [17]:
x[0,1]=100
x

array([[ 12, 100,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [18]:
y = x
y[0,0]=200
x

array([[200, 100,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [19]:
z = x.copy() #copy() function
z[0,0]=500
x

array([[200, 100,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [20]:
y[0,0]=2
x

array([[  2, 100,   2,   4],
       [  7,   6,   8,   8],
       [  1,   6,   7,   7]])

In [22]:
p = np.array([2,5,8,4,3,6,7,8,9])
p

array([2, 5, 8, 4, 3, 6, 7, 8, 9])

In [33]:
q = p.reshape((3,3))   #shaping of multidim arrays
p[:,np.newaxis]

array([[2],
       [5],
       [8],
       [4],
       [3],
       [6],
       [7],
       [8],
       [9]])

In [26]:
s = p.reshape((9,1))
s

array([[2],
       [5],
       [8],
       [4],
       [3],
       [6],
       [7],
       [8],
       [9]])

In [27]:
s

array([[2],
       [5],
       [8],
       [4],
       [3],
       [6],
       [7],
       [8],
       [9]])

In [28]:
p

array([2, 5, 8, 4, 3, 6, 7, 8, 9])

In [29]:
p[np.newaxis,:]

array([[2, 5, 8, 4, 3, 6, 7, 8, 9]])

In [30]:
p[:,np.newaxis]

array([[2],
       [5],
       [8],
       [4],
       [3],
       [6],
       [7],
       [8],
       [9]])

In [47]:
a = np.array([[2,3,4],
             [5,6,7]])
a[:,np.newaxis]

array([[[2, 3, 4]],

       [[5, 6, 7]]])

In [49]:
#Array concatenation
x = np.array([1,2,3])
y= np.array([5,6,7])

z = np.concatenate([x,y])
z

array([1, 2, 3, 5, 6, 7])

In [54]:
u = np.array([[1,2,3],[4,5,6]])
v = np.array([[100,200,300],[400,500,600]])
np.concatenate([u,v])

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300],
       [400, 500, 600]])

In [55]:
np.concatenate([u,v],axis = 1)

array([[  1,   2,   3, 100, 200, 300],
       [  4,   5,   6, 400, 500, 600]])

In [59]:
w = np.array([[1,2,3],[4,5,6]])
d = np.array([[100,200,300]])
np.hstack([w,d])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [60]:
np.vstack([w,d])

array([[  1,   2,   3],
       [  4,   5,   6],
       [100, 200, 300]])

In [76]:
x = [1,2,3,99,99,3,2,1]
x1 , x2, x3 = np.split(x,[3,5])
print(x1,x2,x3)
type(x1)

[1 2 3] [99 99] [3 2 1]


numpy.ndarray

In [83]:
y,z = np.split(x,[1])
print(type(y))
z

<class 'numpy.ndarray'>


array([ 2,  3, 99, 99,  3,  2,  1])

In [84]:
a = np.split(x,[3])
type(a)

list

In [89]:
#vsplit is for vertically  splitting (row-wise splitting)
#vsplit is equivalent to split with axis=0 (default), 
#the array is always split along the first axis regardless of the array dimension.
#
ab = np.array([[12,5,2,4],
              [7,6,8,8],
              [1,6,7,7]])

upper, lower = np.vsplit(ab,[2])
print(upper)
print(type(upper))
print(lower)

[[12  5  2  4]
 [ 7  6  8  8]]
<class 'numpy.ndarray'>
[[1 6 7 7]]


In [92]:
#vertically or clumn wise spilitting is hsplit
left , right = np.hsplit(ab,[2])
print(left)
print(type(left))

[[12  5]
 [ 7  6]
 [ 1  6]]
<class 'numpy.ndarray'>
