In [3]:
lst = list(range(10))
conter = [str(i) for i in lst]
conter

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:
import array
lst= list(range(10))
a = array.array("i",lst)   #i is typecode indicating integers
type(a)
a.__class__

array.array

In [12]:
import numpy as np
#creating arrays from python list
np.array([2,4,3,6,5,4])
np.array([2.3,5,6.2,3])

array([2.3, 5. , 6.2, 3. ])

In [14]:
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [17]:
np.array([range(i,i+5) for i in [2,3,4]])

array([[2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [21]:
np.array([range(a,a+5) for a in [1,2,3]])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [28]:
np.array(['1','4','2'],dtype="int32")

array([1, 4, 2], dtype=int32)

In [29]:
np.zeros(10,dtype="int32")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [30]:
np.zeros(5,dtype="str")

array(['', '', '', '', ''], dtype='<U1')

In [31]:
np.ones(5,dtype="float")

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((2,3), dtype="float32")

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [33]:
np.full((3,5),2.3)

array([[2.3, 2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3, 2.3],
       [2.3, 2.3, 2.3, 2.3, 2.3]])

In [34]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [42]:
np.arange(1,20,2)


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.linspace(10,1,3)

array([10. ,  5.5,  1. ])

In [48]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [51]:
np.random.random((3,3))

array([[0.40276455, 0.87222554, 0.38918465],
       [0.68183848, 0.36512151, 0.55843758],
       [0.93844815, 0.47633002, 0.79922562]])

In [52]:
np.random.random(4)

array([0.70847789, 0.51971132, 0.32020871, 0.83436179])

In [53]:
np.random.random((2,2))

array([[0.24449419, 0.06165391],
       [0.49135514, 0.72515578]])

In [54]:
np.random.normal(0,1,(2,2))

array([[ 1.76569219,  0.00668166],
       [-0.74575621, -0.65099314]])

In [55]:
np.random.normal(1,1,(3,3))

array([[1.40348441, 2.39708657, 1.23965695],
       [0.03960818, 2.04766813, 1.68852759],
       [0.32271118, 1.97898549, 0.78617558]])

In [9]:
import numpy as np
x=np.arange(10)
print(x)
print(x[:4:-2])

[0 1 2 3 4 5 6 7 8 9]
[9 7 5]


In [2]:
import array as a
a.array("i",[1,2,3,4])

array('i', [1, 2, 3, 4])

In [4]:
a.array('d', [2.5, 3.2, 3.3])

array('d', [2.5, 3.2, 3.3])

In [7]:
import numpy as np
np.array([2,3,4],dtype="float32")

array([2., 3., 4.], dtype=float32)

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.full((2,3),8,dtype="int32")

array([[8, 8, 8],
       [8, 8, 8]], dtype=int32)

In [20]:
np.random.random((4,4))

array([[0.937871  , 0.23462729, 0.54555676, 0.3970142 ],
       [0.34236897, 0.01252514, 0.43154132, 0.98896421],
       [0.05554071, 0.15327594, 0.67023797, 0.12211691],
       [0.4202893 , 0.37145874, 0.95730987, 0.39638951]])

In [25]:
np.random.normal(2,1,size=(2,3))

array([[1.16264033, 1.8907781 , 2.30831933],
       [1.27910936, 1.82993349, 2.30603374]])

In [28]:
np.random.normal(2,2,size=(5,2))


array([[ 1.78730118, -1.01007315],
       [ 4.40654997,  3.60576507],
       [ 3.61259239,  2.50253129],
       [-2.3749771 , -0.68913154],
       [ 1.96952549,  2.92676466]])

In [29]:
np.arange(0,5,2)

array([0, 2, 4])

In [31]:
x = np.array([2,3,4],dtype="float32")
x

array([2., 3., 4.], dtype=float32)

In [35]:
x = np.array(([12,5,2,4],[7,6,8,8],[1,6,7,7]),dtype="int32")
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [41]:
np.random.random((2,2))

array([[0.79072186, 0.00761458],
       [0.34831478, 0.44041469]])

In [42]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the given shape,

In [43]:
np.empty((2,2))

array([[0.79072186, 0.00761458],
       [0.34831478, 0.44041469]])

In [63]:
x = np.array(([12,5,2,4],[7,6,8,8],[1,6,7,7]),dtype="int32")
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [65]:
x[:2,:3]  #first two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]], dtype=int32)

In [46]:
x[:1,:4]  #1st row, fourth column

array([[12,  5,  2,  4]], dtype=int32)

In [47]:
x[:3,::2]  #every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]], dtype=int32)

In [48]:
x[::-1,::-1]  #reversed rows and reversed columns

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]], dtype=int32)

In [56]:
x

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]], dtype=int32)

In [57]:
x[::-1,::-2]

array([[7, 6],
       [8, 6],
       [4, 5]], dtype=int32)

In [60]:
x[::1,::-1]  #reversed columns

array([[ 4,  2,  5, 12],
       [ 8,  8,  6,  7],
       [ 7,  7,  6,  1]], dtype=int32)

In [61]:
x[::-1,::1]    #reversed rows

array([[ 1,  6,  7,  7],
       [ 7,  6,  8,  8],
       [12,  5,  2,  4]], dtype=int32)

In [67]:
x[:,1]  

array([5, 6, 6], dtype=int32)