In [1]:
import numpy as np
a=np.array([2,3,4])
a

array([2, 3, 4])

In [2]:
b=np.array([2,3,4,5],dtype="int32")
b

array([2, 3, 4, 5], dtype=int32)

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.zeros(10,dtype="float32")

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [7]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [8]:
np.full(5,5)

array([5, 5, 5, 5, 5])

In [9]:
np.full(5,3.2)

array([3.2, 3.2, 3.2, 3.2, 3.2])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.random.random(5)

array([0.35172389, 0.55699403, 0.57997232, 0.11595418, 0.7755391 ])

In [15]:
np.random.random((2,3))

array([[0.06797692, 0.11958941, 0.00800845],
       [0.17797436, 0.01759902, 0.15673369]])

In [16]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [17]:
np.linspace(1,10,8)

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [23]:
import array
len(array.array("f",[2,3,4]))

3

In [24]:
array.array("d",[4.5,8.8,9.6])

array('d', [4.5, 8.8, 9.6])

In [25]:
np.empty(4)

array([2.8017692e-316, 0.0000000e+000, 1.5810101e-322, 1.0071380e-046])

In [26]:
np.random.randint(10,size=6)

array([3, 1, 3, 9, 0, 0])

In [1]:
np.random.randint(8,size)

NameError: name 'np' is not defined

In [5]:
import numpy as np
a=np.array([[1,2,3],
            [4,2,3]])
print("dimension:",a.ndim)
print("shape: ",a.shape)
print("size: ",a.size)

dimension: 2
shape:  (2, 3)
size:  6


In [10]:
a[:1] #only one dimention indicates row

array([[1, 2, 3]])

In [11]:
a[:]

array([[1, 2, 3],
       [4, 2, 3]])

In [14]:
a[1]

array([4, 2, 3])

In [15]:
a[1,1]

2

In [34]:
a[1,:]     #is same as a[1]

array([4, 2, 3])

In [17]:
a[:1,:1]

array([[1]])

In [18]:
type(a[:1,:1])

numpy.ndarray

In [19]:
a[[1]]

array([[4, 2, 3]])

In [20]:
type(a[[1]])

numpy.ndarray

In [22]:
import array
arr= array.array("i",[2,3,4,5,6,7,8])

In [23]:
arr[1]

3

In [24]:
arr[[1]]

TypeError: array indices must be integers

In [25]:
type(arr[[1]])

TypeError: array indices must be integers

In [26]:
class(arr[[1]])

SyntaxError: invalid syntax (392891693.py, line 1)

In [27]:
a[[1]]

array([[4, 2, 3]])

In [28]:
a[:]

array([[1, 2, 3],
       [4, 2, 3]])

In [29]:
type(a[[1]])

numpy.ndarray

In [30]:
a[:1,:0]

array([], shape=(1, 0), dtype=int64)

In [31]:
a[:,1]

array([2, 2])

In [32]:
a[1,:]

array([4, 2, 3])

In [33]:
a[1]

array([4, 2, 3])

In [36]:
a[:,0]   #first column

array([1, 4])

In [37]:
a[0,:]       #first row

array([1, 2, 3])

In [38]:
a[1,:]

array([4, 2, 3])

In [39]:
a[:,1]

array([2, 2])

In [40]:
a[:,2]

array([3, 3])

In [42]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [2, 3]])

In [43]:
a

array([[1, 2, 3],
       [4, 2, 3]])

In [44]:
a[np.newaxis,:]

array([[[1, 2, 3],
        [4, 2, 3]]])

In [50]:
(a[:,np.newaxis]).shape

(2, 1, 3)

In [48]:
a[:,np.newaxis]

array([[[1, 2, 3]],

       [[4, 2, 3]]])

In [52]:
import numpy as np
arr = np.arange(5*5).reshape(5, 5)
print(arr.shape)

# promoting 2D array to a 5D array
# arr[None, ..., None, None]
arr_5D = arr[np.newaxis,np.newaxis, np.newaxis]

print(arr_5D.shape)


(5, 5)
(1, 1, 1, 5, 5)


In [54]:
(a[:,None]).shape

(2, 1, 3)

In [13]:
import numpy as np
x1=np.array([1,2,3,4,5])
x2=np.array([1,2,3])
new_x2 = x2[:,np.newaxis]
sum = x1+new_x2
sum
new_x2.shape
new_x2

array([[1],
       [2],
       [3]])

In [27]:
A = np.ones((3,4,5,6))
B = np.ones((4,6))
b_new = B[:, np.newaxis, :]
print("b_new: ",b_new.shape)
s=(A + b_new)   # B[:, None, :]
s.shape

b_new:  (4, 1, 6)


(3, 4, 5, 6)

In [17]:
np.newaxis is None

True

In [33]:
A = np.ones((3,4,5,6))
B = np.ones((4,6))
b_new=B[:,None]
print("b_new: ",b_new.shape)
s=(A + b_new)   # B[:, None, :]


b_new:  (4, 1, 6)


In [1]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
np.eye?


Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array o

In [4]:
np.random.randint(1,10,(3,3))

array([[6, 6, 7],
       [8, 6, 4],
       [5, 2, 5]])

In [5]:
# random. randint() is one of the function for doing random sampling in numpy.
#It returns an array of specified shape and fills it with random integers from 
#low (inclusive) to high (exclusive), i.e. in the interval [low, high).

In [6]:
#random.randint(low, high=None, size=None, dtype=int)
#Return random integers from low (inclusive) to high (exclusive).

#Return random integers from the “discrete uniform” distribution of the specified dtype 
#in the “half-open” interval [low, high). If high is None (the default), then results are from [0, low).

In [7]:
np.random.randint(1, [3, 5, 10])

array([2, 4, 1])

In [8]:
np.random.randint([1, 5, 7], 10)

array([3, 6, 8])

In [15]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [16]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [17]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [19]:
np.random.seed(0)
np.random.randint(2,4)

2

In [34]:
np.random.seed(0)
np.random.randint(2,4,2)

array([2, 3])

In [35]:
x = np.array([2,3,4])
x[-1]

4

In [37]:
x[-2]

3